name: Build and Push Frontend Images on Tag

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push-prod:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Set PROD image tag
        id: set-tag
        run: |
          GIT_TAG=${GITHUB_REF#refs/tags/}
          PROD_IMAGE_TAG="prod-${GIT_TAG}"
          echo "PROD_IMAGE_TAG=${PROD_IMAGE_TAG}" >> $GITHUB_ENV
          echo "prod_image_tag=${PROD_IMAGE_TAG}" >> $GITHUB_OUTPUT
      - name: Login to docker registry
        uses: docker/login-action@v4
        with:
          registry: docker-registry.osc.edu
          username: ${{ secrets.OSC_REGISTRY_ROBOT_OSC_USERNAME }}
          password: ${{ secrets.OSC_REGISTRY_ROBOT_OSC_TOKEN }}
      - name: Docker Build and Push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: docker-registry.osc.edu/osc/hpcgpt_frontend:$PROD_IMAGE_TAG
          build-args: |
            NEXT_PUBLIC_KEYCLOAK_URL=${{ vars.KEYCLOAK_URL }}
            NEXT_PUBLIC_KEYCLOAK_ISSUER_URL=${{ vars.ISSUER_URL }}
            NEXT_PUBLIC_USE_OSC_CHAT_CONFIG=${ vars.CHAT_CONFIG }}
